inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 130

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
