name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # Since the name of the matrix job depends on the version, we define another job with a more stable name.
  test_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test Results
    needs: [test]
    steps:
      - run: '[[ "${{ needs.test.result }}" == "success" ]]'
  test:
    runs-on: ubuntu-latest
    services:
      postgis:
        image: mysql:${{matrix.mysql}}
        ports:
          - 3306:3306
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysqlpass
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
    strategy:
      fail-fast: false
      matrix:
        # https://ruby-lang.org/en/downloads/branches
        ruby: ["3.3", "3.2", "3.1"]
        # https://www.postgresql.org/support/versioning/
        mysql: [5.7, 8.0, 8.4, 9.5]
    steps:
      - name: Set Up Actions
        uses: actions/checkout@v4
      - name: Install GEOS
        run: sudo apt-get install libgeos-dev
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Database
        run: |
          mysql -d postgresql://mysql:mysqlpass@localhost:3306/mysql \
            -c "create database rgeo_adapter_test" \
            -c "create database activerecord_unittest" \
            -c "create database activerecord_unittest2"
          for db in rgeo_adapter_test activerecord_unittest activerecord_unittest2; do
            psql -d postgresql://mysql:mysqlpass@localhost:3306/$db -c "create extension postgis"
          done
      - name: Run Tests
        run: bundle exec rake test
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          TESTOPTS: --profile=3
          TEST_TIMEOUT: 30
